[build-system]
requires = [
    'setuptools',
]
build-backend = 'setuptools.build_meta'

[project]
name = 'pttbbs-backend'
version = 'v0.44.3'
description = ''
readme = 'README.md'
authors = [
    {name = 'Chuan-Heng Hsiao', email = 'hsiao.chuanheng@gmail.com'},
]
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
]
dependencies = [
    'fastapi[standard]==0.141.1',
]

[project.scripts]
apidoc = 'apidoc.apidoc:app'

[tool.setuptools.packages.find]
include = [
    'apidoc',
]
exclude = [
    'tests*',
]
